services:
  app:
    container_name: automatons
    image: automatons
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy

networks:
  proxy:
    external: true
