name: Build and Deploy Conway's Game

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: deploy game
        uses: fifsky/ssh-action@master
        with:
          args: '-tt'
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          command: ~/deploy.sh conwaysGame-ts
